theme: minima
title: Nouriverse
author: Nouri HRAIRI
email: medanouar.hrairi@gmail.com
description: Blog about Nouri's thoughts

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  siees # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
